# Generated by Django 3.1.3 on 2020-11-20 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSolvePoscomp', '0003_auto_20201119_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questaotags',
            name='questao_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppSolvePoscomp.questao'),
        ),
        migrations.AlterField(
            model_name='questaotags',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppSolvePoscomp.tag'),
        ),
    ]
