# Generated by Django 3.1.3 on 2020-11-20 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSolvePoscomp', '0004_auto_20201120_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questaotags',
            name='questao_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppSolvePoscomp.questao'),
        ),
        migrations.AlterField(
            model_name='questaotags',
            name='tag_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppSolvePoscomp.tag'),
        ),
    ]
