# Generated by Django 3.1.3 on 2020-11-13 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caderno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('criador_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('alternativa_correta', models.CharField(max_length=1)),
                ('ano', models.IntegerField()),
                ('texto_imagem', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSolvePoscomp.questao')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caderno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSolvePoscomp.caderno')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelacaoCadernoQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caderno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSolvePoscomp.caderno')),
                ('questao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSolvePoscomp.questao')),
            ],
        ),
        migrations.CreateModel(
            name='QuestaoTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSolvePoscomp.questao')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSolvePoscomp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='QuestaoSimulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_selecionada', models.CharField(default='#', max_length=1)),
                ('questao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSolvePoscomp.questao')),
                ('simulado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSolvePoscomp.simulado')),
            ],
        ),
    ]
