# Generated by Django 3.1.3 on 2020-11-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSolvePoscomp', '0007_auto_20201122_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='caderno',
            name='descricao',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='caderno',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
