# Generated by Django 3.1.3 on 2020-11-30 19:24

from django.db import migrations
# from django.core.files import File
# from pathlib import Path
from django.conf import settings
from django.contrib.auth.hashers import make_password

def add_user_poscomp_team(apps, schema_editor):

    User = apps.get_model(settings.AUTH_USER_MODEL)
    user = User.objects.create(
        username = "PoscompTeam",
        password = make_password("PoscompTeam"),
        is_active = True,
        email = "",
    )
    user.save()

def rm_user_poscomp_team(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    user = User.objects.get(username='PoscompTeam')

    user.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('AppSolvePoscomp', '0008_auto_20201125_0832'),
    ]

    operations = [
        migrations.RunPython(add_user_poscomp_team, rm_user_poscomp_team),
    ]
