# Generated by Django 3.1.3 on 2021-01-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSolvePoscomp', '0009_auto_20201130_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='alt_A',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='alt_B',
            field=models.CharField(default='b', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='alt_C',
            field=models.CharField(default='c', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='alt_D',
            field=models.CharField(default='d', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='alt_E',
            field=models.CharField(default='e', max_length=1000),
            preserve_default=False,
        ),
    ]
